### ISSUE TITLE
onedrive

### ISSUE THREAD

**Issue by iwusong** [shirok1/e5-api-renew-scf#1]
有个老哥给了一个e5 账号   为什么用不了onedrive，有什么特殊姿势吗

**Comment by shirok1** [comment]
你先试试能不能登上office.com，然后点开里面的网页版onedrive。我一开始也是不行，但是装office365折腾完一波之后又行了

**Comment by shirok1** [comment]
以及，一般这种账号都是拿来挂OneIndex的，不会直接拿来用，搞不好要弄个OneIndex才能用也是有可能的。[这个版本](https://github.com/qkqpttgf/OneManager-php)的OneIndex可以挂在云函数上，同样也是白嫖免费额度
