### ISSUE TITLE
readme中引用的链接教程似乎都已经失效

### ISSUE THREAD

**Issue by LiuNianJiang** [shirok1/e5-api-renew-scf#2]
作者你好，似乎教程都已经失效了，请问如何填写重定向URL？以及循环周期是否是在腾讯云函数中调整？还是在代码中调整

**Comment by shirok1** [comment]
sorry。。我已经弃坑了。我自己的订阅也已经在去年十二月底掉了

**Comment by shirok1** [comment]
如果你用定时触发器那就在控制台修改，这个很好理解

如果你用随机时间触发，就在ScfOperate.py里面改，单位秒数
下限random_time_lowerlimit默认150
上限random_time_toplimit默认300

**Comment by LiuNianJiang** [comment]
> 如果你用定时触发器那就在控制台修改，这个很好理解
> 
> 如果你用随机时间触发，就在ScfOperate.py里面改，单位秒数
> 下限random_time_lowerlimit默认150
> 上限random_time_toplimit默认300

你好，我尝试将代码和文件复制到腾讯云函数后，我发现运行报错，不知道为何

**Comment by shirok1** [comment]
> > 如果你用定时触发器那就在控制台修改，这个很好理解
> > 
> > 如果你用随机时间触发，就在ScfOperate.py里面改，单位秒数
> > 下限random_time_lowerlimit默认150
> > 上限random_time_toplimit默认300
> 
> 你好，我尝试将代码和文件复制到腾讯云函数后，我发现运行报错，不知道为何

发上来看看

**Comment by LiuNianJiang** [comment]
> > > 如果你用定时触发器那就在控制台修改，这个很好理解
> > > 如果你用随机时间触发，就在ScfOperate.py里面改，单位秒数
> > > 下限random_time_lowerlimit默认150
> > > 上限random_time_toplimit默认300
> > 
> > 
> > 你好，我尝试将代码和文件复制到腾讯云函数后，我发现运行报错，不知道为何
> 
> 发上来看看

https://pan.huang1111.cn/s/bNztY
是这样配置么

**Comment by shirok1** [comment]
> > > > 如果你用定时触发器那就在控制台修改，这个很好理解
> > > > 如果你用随机时间触发，就在ScfOperate.py里面改，单位秒数
> > > > 下限random_time_lowerlimit默认150
> > > > 上限random_time_toplimit默认300
> > > 
> > > 
> > > 你好，我尝试将代码和文件复制到腾讯云函数后，我发现运行报错，不知道为何
> > 
> > 
> > 发上来看看
> 
> https://pan.huang1111.cn/s/bNztY
> 是这样配置么

我看不到你是怎么配置的。。截一下环境变量的图
btw，你可以直接把图片拖进或者粘贴进评论框，不用云盘那么麻烦

**Comment by shirok1** [comment]
https://51.ruyo.net/15646.html
你可以参考这个来获取我说的参数，或者直接用他的方法

**Comment by LiuNianJiang** [comment]
> > > > > 如果你用定时触发器那就在控制台修改，这个很好理解
> > > > > 如果你用随机时间触发，就在ScfOperate.py里面改，单位秒数
> > > > > 下限random_time_lowerlimit默认150
> > > > > 上限random_time_toplimit默认300
> > > > 
> > > > 
> > > > 你好，我尝试将代码和文件复制到腾讯云函数后，我发现运行报错，不知道为何
> > > 
> > > 
> > > 发上来看看
> > 
> > 
> > https://pan.huang1111.cn/s/bNztY
> > 是这样配置么
> 
> 我看不到你是怎么配置的。。截一下环境变量的图
> btw，你可以直接把图片拖进或者粘贴进评论框，不用云盘那么麻烦

请问执行方法这里填的是：index.exe么？

**Comment by shirok1** [comment]
> > > > > > 如果你用定时触发器那就在控制台修改，这个很好理解
> > > > > > 如果你用随机时间触发，就在ScfOperate.py里面改，单位秒数
> > > > > > 下限random_time_lowerlimit默认150
> > > > > > 上限random_time_toplimit默认300
> > > > > 
> > > > > 
> > > > > 你好，我尝试将代码和文件复制到腾讯云函数后，我发现运行报错，不知道为何
> > > > 
> > > > 
> > > > 发上来看看
> > > 
> > > 
> > > https://pan.huang1111.cn/s/bNztY
> > > 是这样配置么
> > 
> > 
> > 我看不到你是怎么配置的。。截一下环境变量的图
> > btw，你可以直接把图片拖进或者粘贴进评论框，不用云盘那么麻烦
> 
> 请问执行方法这里填的是：index.exe么？

是

**Comment by LiuNianJiang** [comment]
好的，我尝试一下，请问权限配置要使用和那个主题一样的么？还是不需要特地使用API权限？

**Comment by shirok1** [comment]
> 好的，我尝试一下，请问权限配置要使用和那个主题一样的么？还是不需要特地使用API权限？

API权限。。把Microsoft Graph全勾上，再加一个PowerBI就行了

**Comment by LiuNianJiang** [comment]
> > 好的，我尝试一下，请问权限配置要使用和那个主题一样的么？还是不需要特地使用API权限？
> 
> API权限。。把Microsoft Graph全勾上，再加一个PowerBI就行了

OK，我尝试一下

**Comment by LiuNianJiang** [comment]
> > 好的，我尝试一下，请问权限配置要使用和那个主题一样的么？还是不需要特地使用API权限？
> 
> API权限。。把Microsoft Graph全勾上，再加一个PowerBI就行了

最多只能选择30个，没办法全部勾选

**Comment by shirok1** [comment]
> > > 好的，我尝试一下，请问权限配置要使用和那个主题一样的么？还是不需要特地使用API权限？
> > 
> > 
> > API权限。。把Microsoft Graph全勾上，再加一个PowerBI就行了
> 
> 最多只能选择30个，没办法全部勾选

```
# 微软api列表，直接复制粘贴自原脚本
api_list = [
    r"https://graph.microsoft.com/v1.0/me/drive/root",
    r"https://graph.microsoft.com/v1.0/me/drive",
    r"https://graph.microsoft.com/v1.0/users",
    r"https://graph.microsoft.com/v1.0/me/messages",
    r"https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messageRules",
    r"https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messageRules",
    r"https://graph.microsoft.com/v1.0/me/drive/root/children",
    r"https://api.powerbi.com/v1.0/myorg/apps",
    r"https://graph.microsoft.com/v1.0/me/mailFolders",
    r"https://graph.microsoft.com/v1.0/me/outlook/masterCategories"
]
```
代码里硬编码的api列表是这样。。你看着办吧
