### ISSUE TITLE
腾讯云测试报错

### ISSUE THREAD

**Issue by hnghng** [shirok1/e5-api-renew-scf#3]
{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 675, in _load\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 655, in _load_unlocked\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 674, in exec_module\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 781, in get_code\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 741, in source_to_code\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 19\n    refresh_token = \"eyJ0eXAiOiJKV1QiLCJub25jZSI6InR0MkNZcWU4d3ZZMzRhWGxGRW1lUFFROW4\n                                                                                   ^\nSyntaxError: EOL while scanning string literal","statusCode":443}

**Comment by shirok1** [comment]
这是你设置环境变量的时候插了特殊字符进去（比如换行符）。把它们粘贴到记事本里面删掉换行再拷回去。
